export declare const cb_BuGn: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_BuPu: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_GnBu: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_OrRd: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_PuBu: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_PuBuGn: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_PuRd: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_RdPu: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_YlGn: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_YlGnBu: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_YlOrBr: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_YlOrRd: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Accent: {
    tags: string[];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Dark2: {
    tags: string[];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Paired: {
    tags: string[];
    12: [string, string, string, string, string, string, string, string, string, string, string, string];
    10: [string, string, string, string, string, string, string, string, string, string];
    11: [string, string, string, string, string, string, string, string, string, string, string];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Pastel1: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Pastel2: {
    tags: string[];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Set1: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Set2: {
    tags: string[];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Set3: {
    tags: string[];
    12: [string, string, string, string, string, string, string, string, string, string, string, string];
    10: [string, string, string, string, string, string, string, string, string, string];
    11: [string, string, string, string, string, string, string, string, string, string, string];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Blues: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Greens: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Greys: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Oranges: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Purples: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Reds: {
    tags: string[];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_BrBG: {
    tags: string[];
    10: [string, string, string, string, string, string, string, string, string, string];
    11: [string, string, string, string, string, string, string, string, string, string, string];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_PiYG: {
    tags: string[];
    10: [string, string, string, string, string, string, string, string, string, string];
    11: [string, string, string, string, string, string, string, string, string, string, string];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_PRGn: {
    tags: string[];
    10: [string, string, string, string, string, string, string, string, string, string];
    11: [string, string, string, string, string, string, string, string, string, string, string];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_PuOr: {
    tags: string[];
    10: [string, string, string, string, string, string, string, string, string, string];
    11: [string, string, string, string, string, string, string, string, string, string, string];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_RdBu: {
    tags: string[];
    10: [string, string, string, string, string, string, string, string, string, string];
    11: [string, string, string, string, string, string, string, string, string, string, string];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_RdGy: {
    tags: string[];
    10: [string, string, string, string, string, string, string, string, string, string];
    11: [string, string, string, string, string, string, string, string, string, string, string];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_RdYlBu: {
    tags: string[];
    10: [string, string, string, string, string, string, string, string, string, string];
    11: [string, string, string, string, string, string, string, string, string, string, string];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_RdYlGn: {
    tags: string[];
    10: [string, string, string, string, string, string, string, string, string, string];
    11: [string, string, string, string, string, string, string, string, string, string, string];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
export declare const cb_Spectral: {
    tags: string[];
    10: [string, string, string, string, string, string, string, string, string, string];
    11: [string, string, string, string, string, string, string, string, string, string, string];
    9: [string, string, string, string, string, string, string, string, string];
    3: [string, string, string];
    4: [string, string, string, string];
    5: [string, string, string, string, string];
    6: [string, string, string, string, string, string];
    7: [string, string, string, string, string, string, string];
    8: [string, string, string, string, string, string, string, string];
};
